spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

repit:
  api-server:
    base-url: ${API_SERVER_URL:http://localhost:8080}
  ai-server:
    base-url: ${AI_SERVER_URL:http://localhost:8000}