spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD:}

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

repit:
  api-server:
    base-url: ${API_SERVER_URL:http://localhost:8080}